apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYXJ0YmFrdWxldiIsInBhc3N3b3JkIjoiZ2hwX24xTHZUQ0g0dDh4SktCdEpwUE5ZQTdxRzluS0pBRTJ3blJtcCIsImVtYWlsIjoiYWRiYWt1bGV2QGdtYWlsLmNvbSIsImF1dGgiOiJZWEowWW1GcmRXeGxkanBuYUhCZmJqRk1kbFJEU0RSME9IaEtTMEowU25CUVRsbEJOM0ZIT1c1TFNrRkZNbmR1VW0xdyJ9fX0=
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
